
package com.llyc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZFWebServiceInterface", targetNamespace = "http://ZFWebService.zigbee.zf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZFWebServiceInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sysReboot", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SysReboot")
    @ResponseWrapper(localName = "sysRebootResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SysRebootResponse")
    public String sysReboot();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getSJJSSZ_ID")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSJJSSZ_ID", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetSJJSSZID")
    @ResponseWrapper(localName = "getSJJSSZ_IDResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetSJJSSZIDResponse")
    public String getSJJSSZID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setXTSZ", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetXTSZ")
    @ResponseWrapper(localName = "setXTSZResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetXTSZResponse")
    public String setXTSZ(
        @WebParam(name = "arg0", targetNamespace = "")
        TWHXTSZ arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSJJSSZ", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetSJJSSZ")
    @ResponseWrapper(localName = "getSJJSSZResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetSJJSSZResponse")
    public String getSJJSSZ();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setSJJSSZ", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetSJJSSZ")
    @ResponseWrapper(localName = "setSJJSSZResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetSJJSSZResponse")
    public String setSJJSSZ(
        @WebParam(name = "arg0", targetNamespace = "")
        TWHSJJSSZ arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setStation", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetStation")
    @ResponseWrapper(localName = "setStationResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetStationResponse")
    public String setStation(
        @WebParam(name = "arg0", targetNamespace = "")
        TJZJBXX arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStations", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetStations")
    @ResponseWrapper(localName = "getStationsResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetStationsResponse")
    public String getStations();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLayerInfo", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetLayerInfo")
    @ResponseWrapper(localName = "getLayerInfoResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetLayerInfoResponse")
    public String getLayerInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getXTSZ_BM")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getXTSZ_BM", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetXTSZBM")
    @ResponseWrapper(localName = "getXTSZ_BMResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetXTSZBMResponse")
    public String getXTSZBM(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getXTSZ_DM")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getXTSZ_DM", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetXTSZDM")
    @ResponseWrapper(localName = "getXTSZ_DMResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetXTSZDMResponse")
    public String getXTSZDM(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setLayer", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetLayer")
    @ResponseWrapper(localName = "setLayerResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetLayerResponse")
    public String setLayer(
        @WebParam(name = "arg0", targetNamespace = "")
        TDMLAYER arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStation", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetStation")
    @ResponseWrapper(localName = "getStationResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetStationResponse")
    public String getStation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostion", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetPostion")
    @ResponseWrapper(localName = "getPostionResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetPostionResponse")
    public String getPostion(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delLayer", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.DelLayer")
    @ResponseWrapper(localName = "delLayerResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.DelLayerResponse")
    public String delLayer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delStationById", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.DelStationById")
    @ResponseWrapper(localName = "delStationByIdResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.DelStationByIdResponse")
    public String delStationById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delStation", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.DelStation")
    @ResponseWrapper(localName = "delStationResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.DelStationResponse")
    public String delStation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLayerById", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetLayerById")
    @ResponseWrapper(localName = "getLayerByIdResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetLayerByIdResponse")
    public String getLayerById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAlarm", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetAlarm")
    @ResponseWrapper(localName = "getAlarmResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetAlarmResponse")
    public String getAlarm();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getXTSZ", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetXTSZ")
    @ResponseWrapper(localName = "getXTSZResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetXTSZResponse")
    public String getXTSZ();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLayer", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetLayer")
    @ResponseWrapper(localName = "getLayerResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetLayerResponse")
    public String getLayer();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStationById", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetStationById")
    @ResponseWrapper(localName = "getStationByIdResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetStationByIdResponse")
    public String getStationById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setSystime", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetSystime")
    @ResponseWrapper(localName = "setSystimeResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.SetSystimeResponse")
    public String setSystime(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getSJJSSZ_SBKEY")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSJJSSZ_SBKEY", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetSJJSSZSBKEY")
    @ResponseWrapper(localName = "getSJJSSZ_SBKEYResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetSJJSSZSBKEYResponse")
    public String getSJJSSZSBKEY(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getqyList", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetqyList")
    @ResponseWrapper(localName = "getqyListResponse", targetNamespace = "http://ZFWebService.zigbee.zf.com/", className = "com.llyc.client.GetqyListResponse")
    public String getqyList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
