
package com.llyc.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZFWebServiceImplService", targetNamespace = "http://ZFWebService.zigbee.zf.com/", wsdlLocation = "http://localhost:8888/ZFServiceImpl?wsdl")
public class ZFWebServiceImplService
    extends Service
{

    private final static URL ZFWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZFWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ZFWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ZFWebService.zigbee.zf.com/", "ZFWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ZFServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZFWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ZFWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ZFWebServiceImplService() {
        super(__getWsdlLocation(), ZFWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ZFWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZFWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ZFWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ZFWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ZFWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZFWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ZFWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZFWebServiceInterface
     */
    @WebEndpoint(name = "ZFWebServiceImplPort")
    public ZFWebServiceInterface getZFWebServiceImplPort() {
        return super.getPort(new QName("http://ZFWebService.zigbee.zf.com/", "ZFWebServiceImplPort"), ZFWebServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFWebServiceInterface
     */
    @WebEndpoint(name = "ZFWebServiceImplPort")
    public ZFWebServiceInterface getZFWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ZFWebService.zigbee.zf.com/", "ZFWebServiceImplPort"), ZFWebServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZFWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ZFWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ZFWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
